---
- name: Install Logstash
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-6.1.3.rpm
    state: present
- name: Configure Logstash
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
- name: Configure Logstash daemon
  replace: path=/etc/systemd/system/logstash.service regexp={{ item.regexp }} replace={{ item.replace }}
  with_items:
  - { regexp: '^User=logstash$', replace: 'User=root'}
  - { regexp: '^Group=logstash$', replace: 'Group=root'}
- name: Start Logstash
  systemd:
    daemon_reload: yes
    name: logstash
    state: restarted