---
- name: Install Logstash
  yum:
    name: https://artifacts.elastic.co/downloads/logstash/logstash-6.1.3.rpm
    state: present
- name: Configure Logstash
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
- name: Start Logstash
  systemd:
    daemon_reload: yes
    name: logstash
    state: restarted