---
- name: Enable Rsyslogd modules
  replace: path=/etc/rsyslog.conf regexp={{ item.regexp }} replace={{ item.replace }}
  with_items:
  - { regexp: '^#\$ModLoad imudp$', replace: '$ModLoad imudp'}
  - { regexp: '^#\$UDPServerRun 514$', replace: '$UDPServerRun 514'}
  - { regexp: '^#\$ModLoad imtcp$', replace: '$ModLoad imtcp'}
  - { regexp: '^#\$InputTCPServerRun 514$', replace: '$InputTCPServerRun 514'}
- name: Configure Rsyslogd
  copy: src={{ item }} dest=/etc/rsyslog.d/{{ item }}
  with_items:
  - 01-json-template.conf
  - 60-output.conf
- name: Start Rsyslod
  systemd:
    daemon_reload: yes
    name: rsyslog
    state: restarted
