---
- name: Install ElasticSearch
  yum:
    name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.3.rpm
    state: present
- name: Start Elasticsearch
  systemd:
    daemon_reload: yes
    name: elasticsearch
    state: restarted
