---
- name: Install Epel
  yum:
    name: epel-release
    state: present
- name: Install Nginx
  yum:
    name: nginx
    state: present
- name: Extract avinetworks website
  unarchive:
    src: avinetworks.tar.gz
    dest: /usr/share/nginx/
- name: Ensure Nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Ensure certificate
  copy:
    src: "{{ item }}.crt"
    dest: /etc/nginx/server.crt
  when: ansible_hostname | search("{{ item }}")
  with_items:
  - server1
  - server2
- name: Ensure key
  copy:
    src: "{{ item }}.pem"
    dest: /etc/nginx/server.key
  when: ansible_hostname | search("{{ item }}")
  with_items:
  - server1
  - server2
  notify:
  - restart nginx